<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_PCP Classes</name>
   <tag></tag>
   <elementGuidId>30b2d6f6-82e6-41fe-bd4a-94b4a3a71ae6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#gppcp</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='gppcp']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#gppcp</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>9bb590ac-1408-47a7-b370-e5721e432b3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn dropdown-toggle btn-colored btn-theme-colored2 mt-15 mt-sm-10 pt-10 pb-10 mousedefault</value>
      <webElementGuid>8f76ed42-1073-4df0-9874-7fcf27630fe4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>dropdown</value>
      <webElementGuid>90c1f3ce-ef4c-4d31-abb7-488e03975ee8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>gppcp</value>
      <webElementGuid>52d422da-eed5-427e-b9b8-c3afd4a6e44a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>PCP Classes
									
									</value>
      <webElementGuid>26c9de48-1223-4950-944c-1520ace69492</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gppcp&quot;)</value>
      <webElementGuid>50612310-f44a-4011-8d06-b0b7bc318a55</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='gppcp']</value>
      <webElementGuid>20c258bf-075e-4531-baec-202307aa3bf7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//nav[@id='menuzord']/div/a</value>
      <webElementGuid>765e9e63-2c5e-4185-8be9-5a234f9498b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'PCP Classes')]</value>
      <webElementGuid>5a70de66-a45b-44d3-9adf-ec15b5aed3e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Duplicate Course Completion'])[1]/following::a[1]</value>
      <webElementGuid>8397493e-6b43-41e9-9329-be45e250bf2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Duplicate Degree Certificate'])[1]/following::a[2]</value>
      <webElementGuid>f451a0d7-b02e-43ec-8d00-b0365328c135</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='C24 BATCH'])[1]/preceding::a[1]</value>
      <webElementGuid>936b5773-e55b-420d-905f-99ce45e5962b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='A23 BATCH'])[1]/preceding::a[2]</value>
      <webElementGuid>72672740-71c1-4e41-a611-631736d702a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='PCP Classes']/parent::*</value>
      <webElementGuid>20363d09-549c-482b-a5ad-fd3c5e37f3f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//nav/div/a</value>
      <webElementGuid>5ad1c535-01ff-4f7d-aef7-d4974fb6923f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'gppcp' and (text() = 'PCP Classes
									
									' or . = 'PCP Classes
									
									')]</value>
      <webElementGuid>cb8c7f37-f012-407e-88fb-923bcf257c57</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
