<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Enrollment Number_regno</name>
   <tag></tag>
   <elementGuidId>5acdc8b1-92d8-4ea0-a34f-69a4438ab04e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;regno&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='regno']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>input[name=&quot;regno&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>64d59f3b-1d2c-4be3-a7db-59f7b1b077ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>bc15d041-4367-4d13-8394-033b4ca3bddb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>regno</value>
      <webElementGuid>95e6495e-ad71-4ac4-b767-b429ef20137a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control w3-border w3-hover-border-cyan</value>
      <webElementGuid>b9b34098-1f0b-4f90-b2a6-9452f57ab4f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;student&quot;)/div[@class=&quot;modal-dialog modal-lg&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;modal-body&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-6&quot;]/form[1]/table[@class=&quot;table&quot;]/tbody[1]/tr[1]/td[2]/input[@class=&quot;form-control w3-border w3-hover-border-cyan&quot;]</value>
      <webElementGuid>a8032609-2bc9-4c01-944d-30adc5bad62b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='regno']</value>
      <webElementGuid>5585f26d-4d20-42b7-8e88-38c74de8ea64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='student']/div/div/div[2]/div/div[2]/form/table/tbody/tr/td[2]/input</value>
      <webElementGuid>6c16e6c4-ea85-4fdb-be44-bd530d6c2443</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>bba7cc25-74d8-4ea9-b2f7-a8fef1fa45ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'regno']</value>
      <webElementGuid>9594a1df-02f6-4b2e-af0e-f02efacf5f0a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
