<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_DOB</name>
   <tag></tag>
   <elementGuidId>429959ca-3a68-4d00-aff5-eff7c9bb5be7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>form > table.table > tbody > tr:nth-of-type(2) > td</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='student']/div/div/div[2]/div/div[2]/form/table/tbody/tr[2]/td</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;DOB&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>ce72d89d-d2f7-4786-8930-aca3e15534ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> DOB</value>
      <webElementGuid>44396964-1780-45db-a6a8-706ca2b492a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;student&quot;)/div[@class=&quot;modal-dialog modal-lg&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;modal-body&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-6&quot;]/form[1]/table[@class=&quot;table&quot;]/tbody[1]/tr[2]/td[1]</value>
      <webElementGuid>d543abdf-1101-4991-9486-1b28745528b1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='student']/div/div/div[2]/div/div[2]/form/table/tbody/tr[2]/td</value>
      <webElementGuid>d1b2f445-f665-41ad-a4d5-d0fa0a6b1326</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Enrollment Number'])[1]/following::td[2]</value>
      <webElementGuid>6db9794e-cd59-4232-b92e-f79bf03b72db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='STUDENT LOGIN'])[1]/following::td[3]</value>
      <webElementGuid>e66da1d6-69a3-41ec-8c8d-ac5760224220</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Password'])[1]/preceding::td[2]</value>
      <webElementGuid>97955cde-2454-48fd-b6c4-922bcbe6557c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='DOB']/parent::*</value>
      <webElementGuid>6beda81c-4a6b-4321-acc6-169ca639d4a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/table/tbody/tr[2]/td</value>
      <webElementGuid>f9724928-81e5-48ae-9063-de486db53a70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = ' DOB' or . = ' DOB')]</value>
      <webElementGuid>a2adf06e-a63a-4a02-bf01-311d67843199</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
