<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Apply</name>
   <tag></tag>
   <elementGuidId>5e3d72eb-56f6-4495-bb5b-d758448e6f1d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>tr:nth-of-type(12) > td:nth-of-type(2) > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='blog']/div/div[2]/div/div/table[2]/tbody/tr[12]/td[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=row[name=&quot;On-line Application for Constitution of Research Advisory Committee Apply&quot;i] >> internal:role=link</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>7c97b306-f1af-4dc1-a7d7-ad0cd853daff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>http://exam.unom.ac.in/phd/PhdConstitution/Frm_Constitution_Login.aspx</value>
      <webElementGuid>d76490a0-4f3c-4398-b145-0c25544747ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>e431baff-52d1-47f3-882f-423261f8eb41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Apply</value>
      <webElementGuid>a25f603d-430e-48d6-a3b8-2ddb8c7dd082</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;blog&quot;)/div[@class=&quot;container pt-20 pb-20&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-12&quot;]/div[@class=&quot;research&quot;]/table[@class=&quot;table table-hover table-bordered&quot;]/tbody[1]/tr[12]/td[2]/a[1]</value>
      <webElementGuid>cbebe70c-bece-4704-8876-c34e7cbd3c66</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='blog']/div/div[2]/div/div/table[2]/tbody/tr[12]/td[2]/a</value>
      <webElementGuid>b92e5658-0946-4480-97f9-18fd4e3ed1f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Apply')])[9]</value>
      <webElementGuid>04375903-73f9-4750-a064-14ad77124c58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='On-line Application for Constitution of Research Advisory Committee'])[1]/following::a[1]</value>
      <webElementGuid>5715374b-4bd8-4912-bf42-f1f61979abad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View'])[5]/following::a[1]</value>
      <webElementGuid>9ab7b506-97b8-4b6f-bb24-b2f7699d39aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Checklist for Submission of Synopsis'])[1]/preceding::a[1]</value>
      <webElementGuid>2d2132eb-ce29-4400-aad6-4e50d258fba4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View'])[6]/preceding::a[1]</value>
      <webElementGuid>8e18d274-d8de-48ab-ae62-38278b03fa88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[@href='http://exam.unom.ac.in/phd/PhdConstitution/Frm_Constitution_Login.aspx']</value>
      <webElementGuid>725522b4-5903-4d7d-b482-3aca483c510e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[12]/td[2]/a</value>
      <webElementGuid>4f315339-c1b3-4573-b22e-8bcef467e934</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'http://exam.unom.ac.in/phd/PhdConstitution/Frm_Constitution_Login.aspx' and (text() = 'Apply' or . = 'Apply')]</value>
      <webElementGuid>bd30f359-dcc4-445c-b368-463f363ef9d8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
