<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Eligibility Condition</name>
   <tag></tag>
   <elementGuidId>0b5cdb4b-2207-45fa-84ac-94588bab9fde</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.view-pdf</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//nav[@id='menuzord-right']/ul/li[7]/ul/li/ul/li/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Eligibility Condition&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>d99b47ba-ef4b-4e79-bb21-1fa612b7b7f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.unom.ac.in/webportal/uploads/admissions/eligibility_condition_2024.pdf</value>
      <webElementGuid>504087ec-a927-4fb8-8663-75a292e06629</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>view-pdf</value>
      <webElementGuid>402ab01e-0882-43e9-b8a5-d51fadb970e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Eligibility Condition</value>
      <webElementGuid>e213dd8b-208a-45e3-8304-1dee332aa137</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menuzord-right&quot;)/ul[@class=&quot;menuzord-menu menuzord-right menuzord-indented scrollable&quot;]/li[7]/ul[@class=&quot;dropdown none&quot;]/li[1]/ul[@class=&quot;dropdown none&quot;]/li[1]/a[@class=&quot;view-pdf&quot;]</value>
      <webElementGuid>df631a6e-9984-4c2d-8873-d8668a3b1dd2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//nav[@id='menuzord-right']/ul/li[7]/ul/li/ul/li/a</value>
      <webElementGuid>afa9915c-d3e2-4153-a400-737521e74cbf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Eligibility Condition')]</value>
      <webElementGuid>516f06a5-0304-487f-b318-21ba6ebdfdd8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Admission'])[1]/following::a[2]</value>
      <webElementGuid>e4192100-b1ef-4a63-bcc5-4cb4a995967f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Organogram'])[2]/following::a[3]</value>
      <webElementGuid>9d08bcae-e098-4ecf-a0bc-b3d3ff97f225</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fee Structure'])[1]/preceding::a[1]</value>
      <webElementGuid>aec9ca45-a41a-49cf-8e68-5c8ba34399dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Eligibility Recognition Certificate'])[1]/preceding::a[2]</value>
      <webElementGuid>3a15e4c5-93ec-49a3-b7e8-98039d5f89a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Eligibility Condition']/parent::*</value>
      <webElementGuid>13383031-265c-4203-899c-f92dd4b66d38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://www.unom.ac.in/webportal/uploads/admissions/eligibility_condition_2024.pdf')]</value>
      <webElementGuid>798fee20-a162-466c-b41f-1e63e4955c00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[7]/ul/li/ul/li/a</value>
      <webElementGuid>f367c207-4969-490f-bcba-75653c4ef5ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://www.unom.ac.in/webportal/uploads/admissions/eligibility_condition_2024.pdf' and (text() = 'Eligibility Condition' or . = 'Eligibility Condition')]</value>
      <webElementGuid>810f7f5a-6a29-4266-b73c-51fd33cc5e44</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
