<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Research</name>
   <tag></tag>
   <elementGuidId>72f6776a-7c7c-4f04-a66f-0cce096800f3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>ul.dropdown.none > li > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//nav[@id='menuzord-right']/ul/li[8]/ul/li/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Research&quot;s]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>16ecdc3c-f170-48c0-bb90-995caa5fc1b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.unom.ac.in/index.php?route=research/research</value>
      <webElementGuid>650835ad-bbf1-48e4-bdbb-e799f090bef2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Research</value>
      <webElementGuid>ba1af1b7-9f11-43db-a9ee-b7a34bbb2e96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menuzord-right&quot;)/ul[@class=&quot;menuzord-menu menuzord-right menuzord-indented scrollable&quot;]/li[8]/ul[@class=&quot;dropdown none&quot;]/li[1]/a[1]</value>
      <webElementGuid>8c60df12-9fed-4497-88d6-2419bf1b4785</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//nav[@id='menuzord-right']/ul/li[8]/ul/li/a</value>
      <webElementGuid>147cb68c-e78f-4195-a903-30953f847e0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Research')])[2]</value>
      <webElementGuid>026c7536-b710-4041-b6f1-cc1b99aa79d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Research'])[1]/following::a[1]</value>
      <webElementGuid>76aadff5-140a-4d69-9d63-7e44d88d7c0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Apply Now'])[1]/following::a[2]</value>
      <webElementGuid>0abfed42-f1e2-45b2-835e-3ea5085353cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='University Departments'])[1]/preceding::a[1]</value>
      <webElementGuid>3865509b-6cc9-4006-b091-859c192d975e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Research Centres'])[1]/preceding::a[2]</value>
      <webElementGuid>29703c17-f810-4247-9270-91a4746c3805</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://www.unom.ac.in/index.php?route=research/research')]</value>
      <webElementGuid>5839f952-4bc6-4e75-9099-c1b5592b4031</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[8]/ul/li/a</value>
      <webElementGuid>0ec91eb8-2100-417d-bf95-2dd023fada18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://www.unom.ac.in/index.php?route=research/research' and (text() = 'Research' or . = 'Research')]</value>
      <webElementGuid>8210be95-5407-421c-8d38-410d02f8c63e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
