<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_View</name>
   <tag></tag>
   <elementGuidId>517e7e7e-f462-45ab-90e5-ddfc726515a2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>tr:nth-of-type(11) > td:nth-of-type(2) > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='blog']/div/div[2]/div/div/table[2]/tbody/tr[11]/td[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=row[name=&quot;Two Credit Course - Research and Public Ethics View&quot;i] >> internal:role=link</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>774a654c-32f8-42f6-9d7a-e6c64e440cab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.unom.ac.in/webportal/uploads/downloads/two-credit-course-guidelines-revised.pdf</value>
      <webElementGuid>1d450ea6-5b58-4357-b0ee-ba9d2e9bda06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>523fb3ed-fce0-48ca-bd89-a76a9fa65212</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>View</value>
      <webElementGuid>27b783f1-080d-44e9-9274-4639b275fb79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;blog&quot;)/div[@class=&quot;container pt-20 pb-20&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-12&quot;]/div[@class=&quot;research&quot;]/table[@class=&quot;table table-hover table-bordered&quot;]/tbody[1]/tr[11]/td[2]/a[1]</value>
      <webElementGuid>4ad69535-bf47-4ba7-a85e-c7bf713fcd7e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='blog']/div/div[2]/div/div/table[2]/tbody/tr[11]/td[2]/a</value>
      <webElementGuid>da3cc5fc-9de9-403e-8aeb-f831e5ddeea8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'View')])[5]</value>
      <webElementGuid>421c8638-c065-4250-95e5-de0159f440ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Two Credit Course - Research and Public Ethics'])[1]/following::a[1]</value>
      <webElementGuid>e1d55189-7be6-4d47-a030-fc5f29b47881</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View'])[4]/following::a[1]</value>
      <webElementGuid>f78c40d4-2f5c-40ad-af84-a7a1c2a45e55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='On-line Application for Constitution of Research Advisory Committee'])[1]/preceding::a[1]</value>
      <webElementGuid>4842840f-33a9-46d0-815e-58bf3d1ad86e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Apply'])[8]/preceding::a[1]</value>
      <webElementGuid>0e21b47a-f2cc-422c-be3a-bf8a57582962</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://www.unom.ac.in/webportal/uploads/downloads/two-credit-course-guidelines-revised.pdf')]</value>
      <webElementGuid>87b3f3a5-2cd0-4fe5-a3c8-ddcfe189933a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[11]/td[2]/a</value>
      <webElementGuid>3dea4923-8f25-46b7-9e32-737b5181af16</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://www.unom.ac.in/webportal/uploads/downloads/two-credit-course-guidelines-revised.pdf' and (text() = 'View' or . = 'View')]</value>
      <webElementGuid>37d9abb3-7ffb-4a5b-af0f-e083b3e92b57</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
