<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_New Registration</name>
   <tag></tag>
   <elementGuidId>6950cd88-4b65-478e-a5c2-3e2cecfbd3c8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ANewReg</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='ANewReg']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;New Registration&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>1f6ffea8-2f18-48b9-aa04-d980fbf23fb3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ANewReg</value>
      <webElementGuid>f0037d8d-20b3-413c-af03-816f2007f156</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:__doPostBack('ANewReg','')</value>
      <webElementGuid>79039fb2-4d87-467c-bb3f-c745cbe9b2b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> New Registration</value>
      <webElementGuid>113ce5d8-1fe6-4353-909a-e2023710cbbb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ANewReg&quot;)</value>
      <webElementGuid>bb35ca3a-8313-43e2-a333-0be82c1f45e9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='ANewReg']</value>
      <webElementGuid>3bb64537-0443-485a-91c7-852cb3100556</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='t1']/a</value>
      <webElementGuid>6c4f3f55-7f29-4218-b9c9-0728d6250f04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'New Registration')]</value>
      <webElementGuid>57613d74-4319-4885-a00b-d842cebec1af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='On-line Application for Constitution of Research Advisory Committee'])[1]/following::a[1]</value>
      <webElementGuid>db883990-bea1-4eb7-b9e5-9067a75a5dc2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Already Registered'])[1]/preceding::a[1]</value>
      <webElementGuid>afbe99b2-6c03-494a-b1ac-59fc9fe7622d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='×'])[1]/preceding::a[2]</value>
      <webElementGuid>c75b753f-ae3b-419e-85bc-5a71ddc0326c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='New Registration']/parent::*</value>
      <webElementGuid>0e804382-c7e4-442e-b2b2-e21f334b8d37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, &quot;javascript:__doPostBack('ANewReg','')&quot;)]</value>
      <webElementGuid>90a1cfae-1bc3-4ec1-81e4-472b943d3d55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a</value>
      <webElementGuid>93602148-fe9c-4612-aa73-c00beaacee39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'ANewReg' and @href = concat(&quot;javascript:__doPostBack(&quot; , &quot;'&quot; , &quot;ANewReg&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;&quot; , &quot;'&quot; , &quot;)&quot;) and (text() = ' New Registration' or . = ' New Registration')]</value>
      <webElementGuid>084540a4-9088-4119-9998-c7b479f660b1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
