<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>center_ENROLMENT NUMBER</name>
   <tag></tag>
   <elementGuidId>0d9b6210-9f54-4151-8dfa-807a9eb3de73</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>td.text > center</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='print_content']/table/tbody/tr/td[2]/form/table/tbody/tr[2]/td/center</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>form[name=&quot;frm&quot;] tbody >> internal:has-text=&quot;IDE - M.B.A JUNE 2023 EXAMINATIONS - REVALUATION RESULT Published on :19-03-2024&quot;i >> center >> nth=1</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>center</value>
      <webElementGuid>cea3d4d9-c605-4893-a16d-6d8ade8c6097</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ENROLMENT NUMBER       </value>
      <webElementGuid>dc68a78f-4a07-40b9-b343-6f183a705bb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;print_content&quot;)/table[1]/tbody[1]/tr[1]/td[2]/form[1]/table[@class=&quot;htdborder&quot;]/tbody[1]/tr[2]/td[@class=&quot;text&quot;]/center[1]</value>
      <webElementGuid>223daee5-5cd9-47cb-bd1b-0231bbf9e3ce</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='print_content']/table/tbody/tr/td[2]/form/table/tbody/tr[2]/td/center</value>
      <webElementGuid>238d0a60-1a95-4cd9-a4ca-7d5e96f36875</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ENROLMENT NUMBER'])[2]/preceding::center[2]</value>
      <webElementGuid>5c76e6aa-78ba-459d-83a4-161c60bcf473</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td/center</value>
      <webElementGuid>471efd46-7f7f-435b-8f6e-44aa9eb89ead</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//center[(text() = 'ENROLMENT NUMBER       ' or . = 'ENROLMENT NUMBER       ')]</value>
      <webElementGuid>d37411a6-df5b-446c-b095-aa6be33040e4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
