<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_ENROLMENT NUMBER_txt_ide_reval</name>
   <tag></tag>
   <elementGuidId>07581b20-7847-4f48-9afd-22069d31e107</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;txt_ide_reval&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='txt_ide_reval']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>input[name=&quot;txt_ide_reval&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b32f6d55-23aa-4c7e-ae3f-383e70e0c42e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txt_ide_reval</value>
      <webElementGuid>5bf8b5e4-7b63-408d-a634-febff5850397</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>textboxes1</value>
      <webElementGuid>3ae55266-659b-4cd2-97a3-90b836b7307e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>d0db4b68-3058-4676-8d65-f4ccc2242b86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>cfb20863-cd0a-4cb5-a9c7-a8586fbd06d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;print_content&quot;)/table[1]/tbody[1]/tr[1]/td[2]/form[1]/table[@class=&quot;htdborder&quot;]/tbody[1]/tr[2]/td[@class=&quot;text&quot;]/center[1]/input[@class=&quot;textboxes1&quot;]</value>
      <webElementGuid>4561be43-311c-434d-98d0-61ea0bc06882</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='txt_ide_reval']</value>
      <webElementGuid>f8f730c1-20bc-4754-a382-973d37f1ede4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='print_content']/table/tbody/tr/td[2]/form/table/tbody/tr[2]/td/center/input</value>
      <webElementGuid>9cb17dcc-3912-4d01-9bbd-1f2e37c38054</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>a65b4a6a-d588-4a7d-9973-c5a74486b5bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'txt_ide_reval']</value>
      <webElementGuid>58e5b24d-22ac-4032-9e39-9286638084c8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
