<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_ENROLMENT NUMBER_btn</name>
   <tag></tag>
   <elementGuidId>de8ae5a7-68dd-47b3-9edf-070b4aeaa40c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;btn&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='btn']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>form[name=&quot;frm&quot;] tbody >> internal:has-text=&quot;IDE - M.B.A JUNE 2023 EXAMINATIONS - REVALUATION RESULT Published on :19-03-2024&quot;i >> input[name=&quot;btn&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a80debf1-c604-4a90-bcf0-d5e4595cbcec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>bd240f11-52f1-4955-b607-5c45fbf67c27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>btn</value>
      <webElementGuid>8f814b6b-9c5e-4bcc-a99e-78f7cab03d53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Submit</value>
      <webElementGuid>99412431-b006-43b4-b447-3991b7a8f499</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>cafd7192-0ed1-46b3-a647-10a3074f1202</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>FncIdeReval();</value>
      <webElementGuid>d084399b-fde3-4571-89bd-534bbb682897</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>buttons1</value>
      <webElementGuid>2be9c57f-ea62-442c-8c78-396383895abb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;print_content&quot;)/table[1]/tbody[1]/tr[1]/td[2]/form[1]/table[@class=&quot;htdborder&quot;]/tbody[1]/tr[2]/td[@class=&quot;text&quot;]/center[1]/input[@class=&quot;buttons1&quot;]</value>
      <webElementGuid>1c05731d-7d09-4fd1-a231-a224c0dba63f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='btn']</value>
      <webElementGuid>17d0f8a9-7281-4fa7-92de-f8be1c507598</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='print_content']/table/tbody/tr/td[2]/form/table/tbody/tr[2]/td/center/input[2]</value>
      <webElementGuid>09f6b0b8-f572-498c-99b7-a396da09aa3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[2]</value>
      <webElementGuid>6f13e419-05da-4470-9afb-97c706ed3e30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @name = 'btn']</value>
      <webElementGuid>6ace3563-9c55-4c1f-87f0-99609afc6911</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
